name: Bug Report
description: Report an issue or problem with a script
title: "BUG: (script name)"
labels: ["bug"]
assignees:
  - 05Konz
body:
  - type: input
    id: script
    attributes:
      label: Script
      description: Which script is causing the problem?
      placeholder: scriptname.js
    validations:
      required: true
  - type: textarea
    id: problem
    attributes:
      label: Problem
      description: What's the problem with the script?
      placeholder: Describe the issue
    validations:
      required: true
  - type: dropdown
    id: method
    attributes:
      label: Method
      description: How did you run the script?
      multiple: true
      options:
        - Imported Bookmarklets.html
        - "Put 'javascript:(code)' in the url bar or a bookmark"
        - Pasted script into console
        - Other (described in Extra Info section)
    validations:
      required: true
  - type: dropdown
    id: type
    attributes:
      label: Type
      description: Unobfuscated or obfuscated
      multiple: true
      options:
        - Unobfuscated
        - Obfuscated
    validations:
      required: true
  - type: textarea
    attributes:
      label: Extra Info
      description: Any extra info (ie screenshots or any important info)
    validations:
      required: false